name: Import imagery

on:
  issues:
    types: [labeled]

jobs:
  import-imagery:
    if: github.event.label.name == 'import-imagery'

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.1.1
      with:
        node-version: "12.x"
        registry-url: https://registry.npmjs.org

    - name: Print a greeting
      env:
        URL: ${{github.event.issue.body}}
      run: |
         $URL
