name: Import imagery

on:
  issues:
    types: [labeled]

jobs:
  import-imagery:
    if: github.event.label.name == 'import-imagery'

    runs-on: ubuntu-latest

    steps:
    - name: Print a greeting
      env:
        URL: ${{github.event.issue.url}}
      run: |
        echo testing url $URL
